# Generated by Django 2.0.2 on 2018-11-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20181110_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='github',
        ),
    ]
