# Generated by Django 2.0.2 on 2018-11-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20181110_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='githublink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
