# Generated by Django 2.0.2 on 2018-11-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_githublink'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hostedprojecturl',
            field=models.CharField(default='', max_length=100),
        ),
    ]
