# Generated by Django 2.0.2 on 2018-11-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_hostedprojecturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
